py_binary(
    name = "rosidl_adapter_wrapper",
    srcs = ["rosidl_adapter_wrapper.py"],
    main = "rosidl_adapter_wrapper.py",
    visibility = ["//visibility:public"],
    deps = ["@ros2_rosidl//:adapter"]
)